---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 1h
  releaseName: flagger
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: flagger
      version: 1.37.0
      interval: 6h 
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flagger-system
      verify: # verify the chart signature with Cosign keyless
        provider: cosign 
  values:
    loglevel: debug
    prometheus:
      install: true
    meshProvider: "kubernetes"
#    meshProvider: "linkerd"
#    namespace: "flagger-system"
#    metricsServer: "http://prometheus.linkerd-viz:9090" # Prometheus Viz from Linkerd
#    linkerdAuthPolicy:
      # linkerdAuthPolicy.create: Whether to create an AuthorizationPolicy in
      # linkerd viz' namespace to allow flagger to reach viz' prometheus service
#      create: true
#      namespace: linkerd-viz      