---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-hr
  path: ./ch4/clusters/security/infra/external-secrets/stores
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 1m0s
  retryInterval: 1m0s
  timeout: 5m0s