apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-viz
  labels:
    linkerd.io/extension: viz
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  interval: 1m0s
  targetNamespace: linkerd-viz
  releaseName: linkerd-viz
  chart:
    spec:
      chart: linkerd-viz
      version: '2024.5.1'
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
  values:
    prometheus:
      enabled: true